# Numpy Snip codes

In [3]:
import numpy as np
import matplotlib.pyplot as plt

#### Snip to create a matrix of N-order polynomial.

**eg: n=3 --> x3  x2  x  1]**

In [4]:

N_pol = 3 # select the order of poly. eg: n=3 --> [x**3  x**2  x  1]

xa = np.array([1,2,3,4,5,6,7,8])
X_new = np.ones_like(xa)

for n_pol in range(1,N_pol+1):
    X_new = np.column_stack([X_new, xa**n_pol])
    #print(X_new[0])

X_new = np.flip(X_new, axis=1) #Now, flip to make higher order axis first.
X_new

array([[  1,   1,   1,   1],
       [  8,   4,   2,   1],
       [ 27,   9,   3,   1],
       [ 64,  16,   4,   1],
       [125,  25,   5,   1],
       [216,  36,   6,   1],
       [343,  49,   7,   1],
       [512,  64,   8,   1]])

***Alternative way to sort items Numpy***

In [5]:
dtype1 = [('distance', float), ('label', int)]
zz =  np.array([(0.0, 6), (4438.931515578946, 9), (6273.341294716875, 9), (2704.942328405543, 4), (4627.564046018164, 1)], dtype = dtype1)  # create a structured array
zz1=np.sort(zz, order='distance')  
print(zz1[0])

(0., 6)


**Element wise Subtraction in numpy**

In [6]:
a = np.array([1,2,3])
b = np.array([1,2,3])

c=a[:, np.newaxis]-b
c

array([[ 0, -1, -2],
       [ 1,  0, -1],
       [ 2,  1,  0]])

#### Sort by Rows and columns

INPUT: [[2, 3, 4]
 [2, 1, 0]
 [1, 1, 1]]

if we use only, Values = Values[Values[:,1].argsort()]

OP:  [[2 1 0]
 [1 1 1]
 [2 3 4]]


if we use, Values = Values[:, Values[**1**, :].argsort()]    **notice the change to 1**

OP:  [[4 3 2]
 [0 1 2]
 [1 1 1]]
 
if we use, 
> Values = Values[Values[:,1].argsort()] 

and then,  
> Values = Values[:, Values[0, :].argsort()]    

**notice the change to 0 in second statement**

OP: [[0 1 2]
 [1 1 1]
 [4 3 2]]

In [ ]:
def srt(Values):
    Values = np.array(Values)
    Values = Values[Values[:,1].argsort()]
    Values = Values[:, Values[0, :].argsort()]
    return Values


def srt(Values):
    if Values.shape[1] > 1:
        Values = Values[Values[:,1].argsort()]
        Values = Values[:, Values[0, :].argsort()]
    else:
        Values = Values[Values[:,0].argsort()]

    return Values